#!/usr/bin/env node

/**
 * parse-vk.js
 *
 * Converts a snarkjs verification_key.json into a Rust file compatible
 * with groth16-solana's Groth16Verifyingkey struct.
 *
 * Usage:
 *   node scripts/parse-vk.js <path-to-verification_key.json>
 *
 * Example:
 *   node scripts/parse-vk.js ../../circuits/build/verification_key.json > programs/proof-of-love/src/verifying_key.rs
 */

const fs = require("fs");
const path = require("path");

const vkPath = process.argv[2];
if (!vkPath) {
  console.error("Usage: node parse-vk.js <path-to-verification_key.json>");
  process.exit(1);
}

const vk = JSON.parse(fs.readFileSync(path.resolve(vkPath), "utf-8"));

/**
 * Convert a decimal string to a 32-byte big-endian array.
 */
function toBE32(decimalStr) {
  let hex = BigInt(decimalStr).toString(16).padStart(64, "0");
  const bytes = [];
  for (let i = 0; i < 64; i += 2) {
    bytes.push(parseInt(hex.slice(i, i + 2), 16));
  }
  return bytes;
}

/**
 * Convert a G1 point [x, y, z] to 64 bytes (big-endian x || y).
 */
function g1ToBytes(point) {
  return [...toBE32(point[0]), ...toBE32(point[1])];
}

/**
 * Convert a G2 point [[x0, x1], [y0, y1], z] to 128 bytes.
 * groth16-solana expects: x1 || x0 || y1 || y0 (big-endian)
 */
function g2ToBytes(point) {
  return [
    ...toBE32(point[0][1]),
    ...toBE32(point[0][0]),
    ...toBE32(point[1][1]),
    ...toBE32(point[1][0]),
  ];
}

/**
 * Format a byte array as Rust array literal with 16 bytes per line.
 */
function formatBytes(bytes, indent = "    ") {
  const lines = [];
  for (let i = 0; i < bytes.length; i += 16) {
    const chunk = bytes.slice(i, i + 16);
    lines.push(
      indent + chunk.map((b) => b.toString().padStart(3, " ")).join(",") + ",",
    );
  }
  return lines.join("\n");
}

// Build the output
const alphaG1 = g1ToBytes(vk.vk_alpha_1);
const betaG2 = g2ToBytes(vk.vk_beta_2);
const gammaG2 = g2ToBytes(vk.vk_gamma_2);
const deltaG2 = g2ToBytes(vk.vk_delta_2);

const icPoints = vk.IC.map((point) => g1ToBytes(point));
const nrPubInputs = vk.IC.length - 1;

let output = `/// AUTO-GENERATED FILE — Do not edit manually.
/// Generated by: node scripts/parse-vk.js ${path.basename(vkPath)}
/// Source: ${path.basename(vkPath)}

use groth16_solana::groth16::Groth16Verifyingkey;

/// Number of public inputs in our circuit:
/// [tier_lower_bound, tier_upper_bound, nullifier, timestamp]
pub const NR_PUBLIC_INPUTS: usize = ${nrPubInputs};

/// Verifying key for the WealthTier Groth16 circuit.
pub const VERIFYING_KEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: NR_PUBLIC_INPUTS,

    vk_alpha_g1: [
${formatBytes(alphaG1, "        ")}
    ],

    vk_beta_g2: [
${formatBytes(betaG2, "        ")}
    ],

    vk_gamma_g2: [
${formatBytes(gammaG2, "        ")}
    ],

    vk_delta_g2: [
${formatBytes(deltaG2, "        ")}
    ],

    vk_ic: &[
`;

for (let i = 0; i < icPoints.length; i++) {
  output += `        [\n${formatBytes(icPoints[i], "            ")}\n        ],\n`;
}

output += `    ],
};
`;

process.stdout.write(output);
